Create sequence app_sequence start with 1
increment by 1
minvalue 1
maxvalue 9999999999;

CREATE TABLE APPLICATIONS(
    APPLICATION_ID INT NOT NULL,
    APPLICATION_NAME VARCHAR2(255) NOT NULL
);

ALTER TABLE APPLICATIONS ADD (
  CONSTRAINT app_pk PRIMARY KEY (APPLICATION_ID));
  
CREATE OR REPLACE TRIGGER app_id_trig 
BEFORE INSERT ON APPLICATIONS 
FOR EACH ROW

BEGIN
  SELECT app_sequence.NEXTVAL
  INTO   :new.APPLICATION_ID
  FROM   dual;
END;
  
-------------------------------------------------------------------------------------------
  
Create sequence prop_sequence start with 1
increment by 1
minvalue 1
maxvalue 9999999999;

CREATE TABLE APPLICATION_PROPERTIES(
    PROPERTY_ID INT NOT NULL,
    PROPERTY_KEY VARCHAR2(255) NOT NULL,
    PROPERTY_VALUE VARCHAR2(255),
    PROPERTY_APPLICATION INT 
);

ALTER TABLE APPLICATION_PROPERTIES ADD (
  CONSTRAINT prop_pk PRIMARY KEY (PROPERTY_ID),
  CONSTRAINT prop_fk FOREIGN KEY(PROPERTY_APPLICATION) REFERENCES APPLICATIONS(APPLICATION_ID)
  );

CREATE OR REPLACE TRIGGER prop_id_trig 
BEFORE INSERT ON APPLICATION_PROPERTIES 
FOR EACH ROW

BEGIN
  SELECT app_sequence.NEXTVAL
  INTO   :new.PROPERTY_ID
  FROM   dual;
END;  

SELECT * FROM APPLICATIONS;

INSERT INTO APPLICATION_PROPERTIES(PROPERTY_KEY, PROPERTY_VALUE, PROPERTY_APPLICATION)
VALUES('TESTKEY', 'TESTVALUE', 1);

SELECT * FROM application_properties;

